customElements.define('site-footer',class extends HTMLElement{connectedCallback(){this.innerHTML='<footer><div class="footer-name">David Johnson Jr.</div><div class="footer-copy">© 2026 · Systems Administrator · Founder · Marine · Full Sail Alumni</div></footer>'}});
function showEdu(idx){document.querySelectorAll('.edu-tab').forEach((t,i)=>t.classList.toggle('active',i===idx));document.querySelectorAll('.edu-panel').forEach((p,i)=>p.classList.toggle('active',i===idx))}
function toggleTheme(){const dark=document.documentElement.getAttribute('data-theme')!=='dark';document.documentElement.setAttribute('data-theme',dark?'dark':'light');localStorage.setItem('theme',dark?'dark':'light');document.getElementById('themeBtn').textContent=dark?'☀ Light':'☾ Dark'}
function toggleMobile(){document.getElementById('mobileMenu').classList.toggle('open')} function closeMobile(){document.getElementById('mobileMenu').classList.remove('open')}
function filterJournal(cat,btn){document.querySelectorAll('.jf-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('[data-cat]').forEach(el=>{el.classList.toggle('hidden',cat!=='all'&&el.dataset.cat!==cat)})}
const posts=[{tag:'Military & Career',date:'January 2026',title:'What the Marine Corps Taught Me About Systems Thinking',body:'<p>The Marine Corps taught me to see systems before I ever studied them formally. Every team, network, supply chain, and project has roles, dependencies, pressure points, and failure risks. That mindset now shapes how I approach IT, business, and creative work.</p>'},{tag:'Education',date:'January 2026',title:'Graduating My First Master's Degree While on Active Duty',body:'<p>Completing a graduate degree while on active duty required discipline over motivation. The biggest lesson was that momentum is protected through structure, not convenience.</p>'},{tag:'Entrepreneurship',date:'2025',title:'Founding Advantage Studios',body:'<p>Advantage Studios started from a real gap: creative talent often lacks the technical and operational infrastructure needed to execute professionally. The company exists to close that gap.</p>'}];
function openPost(i){const p=posts[i];modalTag.textContent=p.tag;modalTitle.textContent=p.title;modalDate.textContent=p.date;modalBody.innerHTML=p.body;modalOverlay.classList.add('open');document.body.style.overflow='hidden'}
function closeModal(e){if(!e||e.target===modalOverlay){modalOverlay.classList.remove('open');document.body.style.overflow=''}}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const savedTheme=localStorage.getItem('theme');if(savedTheme){document.documentElement.setAttribute('data-theme',savedTheme);themeBtn.textContent=savedTheme==='dark'?'☀ Light':'☾ Dark'}
const current=(location.pathname.split('/').pop()||'index.html').replace('.html',''); const map={index:'home'}; const key=map[current]||current; const active=document.getElementById('nav-'+key); if(active) active.classList.add('nav-active');
